version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Africa/Johannesburg"
    open-pull-requests-limit: 5
    reviewers:
      - "SOVRN144"
    commit-message:
      prefix: "chore(deps)"
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "@types/*"
          - "eslint*"
          - "vitest"
          - "@vitest/*"
          - "@typescript-eslint/*"
          - "prettier*"
          - "prettier"
          - "typescript"
    ignore:
      - dependency-name: "eslint"
        versions:
          - "9.x"
      - dependency-name: "vitest"
        versions:
          - "3.x"
      - dependency-name: "@typescript-eslint/*"
        versions:
          - "8.x"
      - dependency-name: "@vitest/coverage-v8"
        versions:
          - "3.x"
      - dependency-name: "@types/node"
        versions:
          - "21.x"
          - "22.x"
          - "23.x"
          - "24.x"
      - dependency-name: "eslint-plugin-security"
        versions:
          - "3.x"   # flat-config only, requires ESLint 9
