name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      PUBLIC_URL:
        description: 'Base URL (e.g., https://<ngrok>.ngrok-free.dev)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install
      - run: npm run typecheck
      - run: npm run build

  smoke:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 30
    env:
      # Safe to expose; used by the server. Token is optional.
      CANVAS_BASE_URL: ${{ vars.CANVAS_BASE_URL }}
      CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Build
        run: |
          npm ci || npm install
          npm run typecheck
          npm run build

      - name: Start MCP server
        run: |
          set -euo pipefail
          LOG_LEVEL=error NODE_ENV=test node dist/http.js > server.log 2>&1 &
          echo $! > server.pid

      - name: Wait for server (http readiness)
        timeout-minutes: 2
        run: |
          set -euo pipefail
          for i in $(seq 1 60); do
            if curl -fsS http://127.0.0.1:8787/mcp >/dev/null 2>&1; then
              echo "Server is ready"
              exit 0
            fi
            sleep 1
          done
          echo "Server did not become ready in time"
          echo "---- server.log (tail) ----"
          tail -n 200 server.log || true
          exit 1

      - name: Install CLI deps
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run tests
        run: |
          npm test

      # Minimal smoke: initialize → tools/list → echo
      - name: Smoke test (initialize → tools/list → echo)
        run: |
          set -euo pipefail
          H=$(mktemp)
          curl -fsS -D "$H" \
            -H 'Accept: application/json, text/event-stream' \
            -H 'Content-Type: application/json' \
            --data '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
            http://127.0.0.1:8787/mcp >/dev/null
          SID=$(awk -F': *' 'tolower($1)=="mcp-session-id"{print $2}' "$H" | tr -d '\r')

          curl -fsS http://127.0.0.1:8787/mcp \
            -H "Mcp-Session-Id: $SID" \
            -H 'Content-Type: application/json' \
            --data '{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}' | jq . >/dev/null

          curl -fsS http://127.0.0.1:8787/mcp \
            -H "Mcp-Session-Id: $SID" \
            -H 'Content-Type: application/json' \
            --data '{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"echo","arguments":{"text":"ci ping"}}}' \
            | jq -r '.result.content[0].text' | grep -q '^ci ping$'

      # Always stop server (fix duplicate `fi`, kill correct process)
      - name: Stop server
        if: always()
        run: |
          set -euo pipefail
          if [ -f server.pid ]; then
            kill "$(cat server.pid)" || true
            rm -f server.pid
          fi
          pkill -f "node dist/http.js" || true
          [ -f server.log ] && tail -n +200 server.log || true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            server.log
            init.json

  smoke-canvas:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ vars.CANVAS_BASE_URL != '' }}
    env:
      CANVAS_BASE_URL: ${{ vars.CANVAS_BASE_URL }}
      CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install

      - name: Check Canvas envs
        id: canvas_env
        run: |
          if [ -z "${CANVAS_BASE_URL:-}" ] || [ -z "${CANVAS_TOKEN:-}" ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "Canvas envs missing; skipping Canvas smoke."
          fi

      - name: Install CLI deps
        if: steps.canvas_env.outputs.skip != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y jq netcat-openbsd

      - name: Start server
        if: steps.canvas_env.outputs.skip != 'true'
        run: |
          nohup npx tsx src/http.ts > server.log 2>&1 &
          echo $! > server.pid
          timeout 15 bash -c 'until nc -z 127.0.0.1 8787; do sleep 0.5; done'

      - name: Canvas smoke (courses → modules)
        if: steps.canvas_env.outputs.skip != 'true'
        run: |
          set -euo pipefail
          H=$(mktemp)
          curl -sD "$H" -H 'Accept: application/json, text/event-stream' \
               -H 'Content-Type: application/json' \
               --data '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
               http://127.0.0.1:8787/mcp | jq . > init.json
          SESSION=$(awk -F': *' 'tolower($1)=="mcp-session-id" {print $2}' "$H" | tr -d '\r')
          test -n "$SESSION"
          TOOLS=$(curl -s http://127.0.0.1:8787/mcp \
            -H 'Accept: application/json, text/event-stream' \
            -H 'Content-Type: application/json' \
            -H "Mcp-Session-Id: $SESSION" \
            --data '{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}')
          echo "$TOOLS" | jq .
          echo "$TOOLS" | jq -e '.result.tools | map(.name=="list_courses") | any'
          curl -sS http://127.0.0.1:8787/mcp \
            -H 'Accept: application/json, text/event-stream' \
            -H 'Content-Type: application/json' \
            -H "Mcp-Session-Id: $SESSION" \
            --data '{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"list_courses","arguments":{}}}' | jq .

      - name: Stop server if running
        if: always() && steps.canvas_env.outputs.skip != 'true'
        run: |
          if [ -f server.pid ]; then kill "$(cat server.pid)" || true; fi
          pkill -f "tsx src/http.ts" || true

      - name: Upload logs
        if: always() && steps.canvas_env.outputs.skip != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: canvas-ci-logs
          path: |
            server.log
            init.json

  public_smoke:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.PUBLIC_URL != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install
      - name: Public smoke
        env:
          PUBLIC_BASE: ${{ github.event.inputs.PUBLIC_URL }}
        run: bash scripts/smoke-public.sh
