name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      PUBLIC_URL:
        description: 'Base URL (e.g., https://<ngrok>.ngrok-free.dev)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install
      - run: npm run typecheck
      - run: npm run build

  smoke:
    runs-on: ubuntu-latest
    needs: build
    env:
      # Safe to expose; used by the server. Token is optional.
      CANVAS_BASE_URL: ${{ vars.CANVAS_BASE_URL }}
      CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install

      - name: Install CLI deps
        run: |
          sudo apt-get update
          sudo apt-get install -y jq netcat-openbsd

      - name: Start server
        run: |
          set -euo pipefail
          nohup npx tsx src/http.ts > server.log 2>&1 &
          echo $! > server.pid
          # Active readiness probe: try initialize up to 30s
          ready=0
          for i in $(seq 1 30); do
            if curl -sSf -H 'Accept: application/json, text/event-stream' \
                   -H 'Content-Type: application/json' \
                   --data '{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
                   http://127.0.0.1:8787/mcp >/dev/null; then
              ready=1; break
            fi
            sleep 1
          done
          if [ "$ready" -ne 1 ]; then
            echo "Server never responded to initialize within 30s"
            echo "----- server.log -----"
            tail -n +1 server.log || true
            exit 1
          fi
          # Do a proper initialize to capture the session header
          H=$(mktemp)
          curl -sD "$H" -H 'Accept: application/json, text/event-stream' \
               -H 'Content-Type: application/json' \
               --data '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
               http://127.0.0.1:8787/mcp | jq . > init.json
          awk -F': *' 'tolower($1)=="mcp-session-id" {print $2}' "$H" | tr -d '\r' > session.txt
          test -s session.txt

      - name: Smoke test (tools/list → echo)
        run: |
          set -euo pipefail
          SESSION=$(cat session.txt)
          LIST=$(curl -sS http://127.0.0.1:8787/mcp \
            -H 'Accept: application/json, text/event-stream' \
            -H 'Content-Type: application/json' \
            -H "Mcp-Session-Id: $SESSION" \
            --data '{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}')
          echo "$LIST" | jq .
          # portable jq: map(..)|any
          echo "$LIST" | jq -e '.result.tools | map(.name=="echo") | any'
          ECHO=$(curl -sS http://127.0.0.1:8787/mcp \
            -H 'Accept: application/json, text/event-stream' \
            -H 'Content-Type: application/json' \
            -H "Mcp-Session-Id: $SESSION" \
            --data '{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"echo","arguments":{"text":"hi"}}}')
          echo "$ECHO" | jq -e '.result.content[0].text == "hi"'

      - name: Stop server if running
        if: always()
        run: |
          set +e
          if [ -f server.pid ]; then
            kill "$(cat server.pid)" || true
          fi
          pkill -f "tsx src/http.ts" || true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            server.log
            init.json
            session.txt

  public_smoke:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.PUBLIC_URL != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install
      - name: Public smoke
        env:
          PUBLIC_BASE: ${{ inputs.PUBLIC_URL }}
        run: bash scripts/smoke-public.sh

  smoke-canvas:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ vars.CANVAS_BASE_URL != '' }}
    env:
      CANVAS_BASE_URL: ${{ vars.CANVAS_BASE_URL }}
      CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install

      - name: Check Canvas envs
        id: canvas_env
        run: |
          if [ -z "${CANVAS_BASE_URL:-}" ] || [ -z "${CANVAS_TOKEN:-}" ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "Canvas envs missing; skipping Canvas smoke."
          fi

      - name: Install CLI deps
        if: steps.canvas_env.outputs.skip != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y jq netcat-openbsd

      - name: Start server
        if: steps.canvas_env.outputs.skip != 'true'
        run: |
          nohup npx tsx src/http.ts > server.log 2>&1 &
          echo $! > server.pid
          timeout 15 bash -c 'until nc -z 127.0.0.1 8787; do sleep 0.5; done'

      - name: Canvas smoke (courses → modules)
        if: steps.canvas_env.outputs.skip != 'true'
        run: |
          set -euo pipefail
          H=$(mktemp)
          curl -sD "$H" -H 'Accept: application/json, text/event-stream' \
               -H 'Content-Type: application/json' \
               --data '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
               http://127.0.0.1:8787/mcp | jq . > init.json
          SESSION=$(awk -F': *' 'tolower($1)=="mcp-session-id" {print $2}' "$H" | tr -d '\r')
          test -n "$SESSION"
          TOOLS=$(curl -s http://127.0.0.1:8787/mcp \
            -H 'Accept: application/json, text/event-stream' \
            -H 'Content-Type: application/json' \
            -H "Mcp-Session-Id: $SESSION" \
            --data '{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}')
          echo "$TOOLS" | jq .
          echo "$TOOLS" | jq -e '.result.tools | map(.name=="list_courses") | any'
          curl -sS http://127.0.0.1:8787/mcp \
            -H 'Accept: application/json, text/event-stream' \
            -H 'Content-Type: application/json' \
            -H "Mcp-Session-Id: $SESSION" \
            --data '{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"list_courses","arguments":{}}}' | jq .

      - name: Stop server if running
        if: always() && steps.canvas_env.outputs.skip != 'true'
        run: |
          if [ -f server.pid ]; then kill "$(cat server.pid)" || true; fi
          pkill -f "tsx src/http.ts" || true

      - name: Upload logs
        if: always() && steps.canvas_env.outputs.skip != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: canvas-ci-logs
          path: |
            server.log
            init.json

  public_smoke:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.PUBLIC_URL != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci || npm install
      - name: Public smoke
        env:
          PUBLIC_BASE: ${{ inputs.PUBLIC_URL }}
        run: bash scripts/smoke-public.sh
